spring:
  application:
    name: HMediaCenterServer

  datasource:
    url: jdbc:mysql://localhost:3306/h_media_center_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  packages-to-scan: com.lake.hmediacenterserver.controller
